// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: chatroom.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NewRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commandid string   `protobuf:"bytes,1,opt,name=commandid,proto3" json:"commandid,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	From      string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Keywords  []string `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *NewRoom) Reset() {
	*x = NewRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatroom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRoom) ProtoMessage() {}

func (x *NewRoom) ProtoReflect() protoreflect.Message {
	mi := &file_chatroom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRoom.ProtoReflect.Descriptor instead.
func (*NewRoom) Descriptor() ([]byte, []int) {
	return file_chatroom_proto_rawDescGZIP(), []int{0}
}

func (x *NewRoom) GetCommandid() string {
	if x != nil {
		return x.Commandid
	}
	return ""
}

func (x *NewRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewRoom) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *NewRoom) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type GetRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId string `protobuf:"bytes,1,opt,name=commandId,proto3" json:"commandId,omitempty"`
}

func (x *GetRoom) Reset() {
	*x = GetRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatroom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoom) ProtoMessage() {}

func (x *GetRoom) ProtoReflect() protoreflect.Message {
	mi := &file_chatroom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoom.ProtoReflect.Descriptor instead.
func (*GetRoom) Descriptor() ([]byte, []int) {
	return file_chatroom_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoom) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ResRooms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomList []*RoomInfo `protobuf:"bytes,1,rep,name=roomList,proto3" json:"roomList,omitempty"`
}

func (x *ResRooms) Reset() {
	*x = ResRooms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatroom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResRooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResRooms) ProtoMessage() {}

func (x *ResRooms) ProtoReflect() protoreflect.Message {
	mi := &file_chatroom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResRooms.ProtoReflect.Descriptor instead.
func (*ResRooms) Descriptor() ([]byte, []int) {
	return file_chatroom_proto_rawDescGZIP(), []int{2}
}

func (x *ResRooms) GetRoomList() []*RoomInfo {
	if x != nil {
		return x.RoomList
	}
	return nil
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Keywords  []string `protobuf:"bytes,2,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
	Starttime string   `protobuf:"bytes,3,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Hoster    string   `protobuf:"bytes,4,opt,name=hoster,proto3" json:"hoster,omitempty"`
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatroom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chatroom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_chatroom_proto_rawDescGZIP(), []int{3}
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *RoomInfo) GetStarttime() string {
	if x != nil {
		return x.Starttime
	}
	return ""
}

func (x *RoomInfo) GetHoster() string {
	if x != nil {
		return x.Hoster
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nick string `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatroom_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatroom_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chatroom_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *ChatMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_chatroom_proto protoreflect.FileDescriptor

var file_chatroom_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x6b, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x52, 0x6f, 0x6f, 0x6d, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x22, 0x27, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x70, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74,
	0x65, 0x72, 0x22, 0x35, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_chatroom_proto_rawDescOnce sync.Once
	file_chatroom_proto_rawDescData = file_chatroom_proto_rawDesc
)

func file_chatroom_proto_rawDescGZIP() []byte {
	file_chatroom_proto_rawDescOnce.Do(func() {
		file_chatroom_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatroom_proto_rawDescData)
	})
	return file_chatroom_proto_rawDescData
}

var file_chatroom_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chatroom_proto_goTypes = []interface{}{
	(*NewRoom)(nil),     // 0: pb.newRoom
	(*GetRoom)(nil),     // 1: pb.getRoom
	(*ResRooms)(nil),    // 2: pb.resRooms
	(*RoomInfo)(nil),    // 3: pb.roomInfo
	(*ChatMessage)(nil), // 4: pb.chatMessage
}
var file_chatroom_proto_depIdxs = []int32{
	3, // 0: pb.resRooms.roomList:type_name -> pb.roomInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatroom_proto_init() }
func file_chatroom_proto_init() {
	if File_chatroom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chatroom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatroom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatroom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResRooms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatroom_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatroom_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatroom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatroom_proto_goTypes,
		DependencyIndexes: file_chatroom_proto_depIdxs,
		MessageInfos:      file_chatroom_proto_msgTypes,
	}.Build()
	File_chatroom_proto = out.File
	file_chatroom_proto_rawDesc = nil
	file_chatroom_proto_goTypes = nil
	file_chatroom_proto_depIdxs = nil
}
